name: Push PHP 8.0-fpm to GitHub Container Registry

on:
  push:
    branches:
      - master
    paths:
      - 8.0-fpm/Dockerfile

env:
  DOCKERFILE: ./8.0-fpm/Dockerfile
  IMAGE_ID: ghcr.io/${{ github.repository_owner }}/php
  VERSION: 8.0-fpm

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out github repository
        uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.SECRET_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: Build PHP image
        run: docker build . --file $DOCKERFILE --tag php
      - name: Push PHP image
        run: |
          docker tag php $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
