name: Push to GitHub Container Registry

on:
  push:
    branches: [master]

env:
  COMPOSER_VERSION: 2.0.8

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: testing
        run: git describe --tags
